export const productList = [
  {
    id: 1,
    title: "Skullcandy - Crusher anc 2 wireless headphones",
    price: 299.99,
    img: "/images/products/headphone01.png",
    stars: 4.5,
    tag: "NEW",
    sale: true,
    saleValue: 20,
  },
  {
    id: 2,
    title: "Beats Studio Pro",
    price: 349.99,
    img: "/images/products/headphone-beatspro.png",
    stars: 4.5,
    tag: "NEW",
    sale: true,
    saleValue: 30,
  },
  {
    id: 3,
    title: "Sony - WH-CH720N Wireless Noise Canceling",
    price: 149.99,
    img: "/images/products/sony-headphone.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 0,
  },
  {
    id: 4,
    title: "Skullcandy - Rail True Wireless Earbuds",
    price: 79.99,
    img: "/images/products/skullcandy-rail-wireless-earbuds.png",
    stars: 5,
    tag: "NEW",
    sale: true,
    saleValue: 10,
  },
  {
    id: 5,
    title: "QCY - HT05",
    price: 44.99,
    img: "/images/products/qcy-ht05.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 0,
  },
  {
    id: 6,
    title: "JBL - T520",
    price: 49.95,
    img: "/images/products/jbl-t520.png",
    stars: 4,
    tag: "NEW",
    sale: false,
    saleValue: 0,
  },
  {
    id: 6,
    title: "Bose QuietConfort Headphone",
    price: 349.99,
    img: "/images/products/bose-quietconfort.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 7,
    title: "Apple Airpods Max",
    price: 549.0,
    img: "/images/products/airpods-max.png",
    stars: 5,
    tag: "HOT",
    sale: true,
    saleValue: 20,
  },
  {
    id: 8,
    title: "Edifier W110T",
    price: 80.99,
    img: "/images/products/edifier-w110t.png",
    stars: 4,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 9,
    title: "Apple Airpods Pro",
    price: 249.0,
    img: "/images/products/airpods-pro.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 10,
    title: "AKG Y600",
    price: 349.99,
    img: "/images/products/akg-y600.png",
    stars: 4,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 11,
    title: "Beats Fit Pro",
    price: 199.99,
    img: "/images/products/beats-fit-pro.png",
    stars: 4.5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 12,
    title: "QCY H2",
    price: 100.99,
    img: "/images/products/qcy-h2.png",
    stars: 4,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 13,
    title: "JBL Reflect Flow Pro+",
    price: 129.99,
    img: "/images/products/jbl-reflect-low-pro.png",
    stars: 4,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 14,
    title: "Jabra Evolve2 85",
    price: 373.00,
    img: "/images/products/jabra-evolve2.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 0,
  },
];

export const usersList = [
  {
    id: "0001",
    name: "Henrique William Oliveira da Silva",
    username: 'sucodeuvahj',
    password: "Teste@123",
    email: "os.heriquewilliam@gmail.com",
    lists: [{ productWish: ["12", "4"] }, { productBag: ["10", "8"] }],
  },
];
